title = "Maple First Inc."
baseURL = "https://maplefirstinc.com"
languageCode = "en-us"
theme = "ananke" #"gohugo-theme-ananke"
#themesDir = "../.." Commented by Hiren

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
#Added by Hiren
#disqusShortname = "HS"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  #Added by Hiren
  #commentoEnable = true (This when enabled with disqusShortname will show comments on your posts)
  #
  favicon = ""
  site_logo = "" #Hiren - Add your own logo.You can replace the title of your site in the top left corner of each page with your own logo
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  #twitter = "https://twitter.com/GoHugoIO"
  twitter = "https://twitter.com/"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://linkedin.com"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  #featured_image = "/images/maple-first-logo.jpg"
  recent_posts_number = 2
